---
- name: Create LUKS Containers
  when:
    - ansible_nodename != "localhost"
    - run_extra_debug | default(false) | bool
  tags:
    - notag
  block:

    - name: Set correct crypt container backing device
      ansible.builtin.set_fact:
        lvm_crypt_backingdevice:  "{{ (disk_by_id | length | int == 2) | ternary( 'UUID='+(lvm_partition_uuids.0|default('')) , '/dev/md/lvm') }}"

    - name: Debug Output lvm_crypt_backingdevice
      ansible.builtin.debug:
        msg: "{{ lvm_crypt_backingdevice }}" 