---
- name: Create LUKS Containers
  when:
    - ansible_nodename != "localhost"
    - run_extra_debug | default(false) | bool
  tags:
    - notag
  block:

    - name: Debug Output of joind list
      ansible.builtin.debug:
        msg: "{{ disk_by_id | list | product([boot_partition, swap_partition, lvm_partition]) | map('join','-part') }}"

    - name: Debug Output of every item in joined list
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop:
        "{{ disk_by_id | list | product([boot_partition, swap_partition, lvm_partition]) | map('join','-part') }}"