---
- name: Create LUKS Containers
  when:
    - ansible_nodename != "localhost"
  tags:
    - notag
  block:
    - name: Try to get all mounts
      ansible.builtin.mount_facts:
        include_aggregate_mounts: true
        sources: all
    # - name: Update facts module
    #   setup:
    - name: Debug Output
      ansible.builtin.debug:
        msg: "{{ ansible_facts['mount_points'] }}"
      when:
        - debug | default(false)
    - name: Binding virtual file systems
      ansible.posix.mount:
        path: "{{ item.target }}"
        src: "{{ item.source }}"
        fstype: "{{ item.fstype }}"
        opts: "{{ item.options }}"
        state: ephemeral
      loop:
        - { options: '',     fstype: 'proc',   source: '/proc', target: '/mnt/proc'}
        - { options: '',     fstype: 'sysfs',  source: 'sys',   target: '/mnt/sys'}
        - { options: 'bind', fstype: '',       source: '/dev',  target: '/mnt/dev'}
        - { options: '',     fstype: 'devpts', source: 'pts',   target: '/mnt/dev/pts'}
      when:
        - item.target not in ansible_facts['mount_points']

