---
# [ Create Datasets for Filesystem ]###########################################
- name: Create Datasets for Filesystem Block
  when:
    - ansible_nodename != "localhost"
  tags:
    - create_datasets
  block:
    - name: Debug Datasets for Filesystem list
      ansible.builtin.debug:
        msg: "zfs create {{ item }}"
      loop:
        "{{ datasets_to_create }}"
      when:
        debug|default(false)

    - name: Create Datasets for Filesystem list
      ansible.builtin.command:
        "zfs create {{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      loop:
        "{{ datasets_to_create }}"
      loop_control:
        label: "{{ item }}"

    - name: Create Directories on mount points and set permissions
      ansible.builtin.file:
        state: directory
        path: "{{ mount_path.path }}"
        mode: "{{ mount_path.mode }}"
      loop:
        - { path: "{{ live_cd_mountpoint }}/root", mode: "700" }
        - { path: "{{ live_cd_mountpoint }}/var/tmp", mode: "1777" }
        - { path: "{{ live_cd_mountpoint }}/run/lock", mode: "755" }
        - { path: "{{ live_cd_mountpoint }}/etc/zfs", mode: "755" }
      loop_control:
        loop_var: mount_path
        label: "{{ mount_path.path }}"

