---
###############################################################################
# [ Should be in chroot env now ]##############################################

- name: Configure new system in chroot environment
  when:
    - ansible_nodename != "localhost"
  tags:
    - config_system
  block:
    - name: Ensure all packages are up to date
      ansible.builtin.apt:
        upgrade: safe
        force_apt_get: true
        autoclean: true
        autoremove: true
        update_cache: true

    - name: Install some requirements
      ansible.builtin.apt:
        name:
          - console-setup
          - locales
          - dpkg-dev
          - debconf
          - debconf-utils
          - mdadm
          - dosfstools
        state: present
        install_recommends: false

    - name: Purge os-prober
      ansible.builtin.apt:
        name:
          - os-prober
        state: absent
        purge: true
      when:
        - ansible_os_family == "Debian"
        - remove_os_prober == true

    - name: Ensure the requested locale exists
      community.general.locale_gen:
        name: "{{ item }}"
        state: present
      loop:
        - "{{ default_locale }}"

    - name: Set default locale
      ansible.builtin.debconf:
        name: locales
        question: locales/default_environment_locale
        value: "{{ default_locale }}"
        vtype: select
      notify: reconf locales

    - name: Configure locales to generate
      ansible.builtin.debconf:
        name: locales
        question: locales/locales_to_be_generated
        value: "{{ default_locale }} UTF-8"
        vtype: multiselect
      notify: reconf locales

    - name: Set timezone area
      ansible.builtin.debconf:
        name: tzdata
        question: tzdata/Areas
        value: "{{ timezone_area }}"
        vtype: select
      notify: reconf tzdata

    - name: Set timezone city
      ansible.builtin.debconf:
        name: tzdata
        question: "tzdata/Zones/{{ timezone_area }}"
        value: "{{ timezone_city }}"
        vtype: select
      notify: reconf tzdata

    - name: Set timezone UTC
      ansible.builtin.debconf:
        name: tzdata
        question: tzdata/Zones/Etc
        value: UTC
        vtype: select
      notify: reconf tzdata
    
    # https://serverfault.com/questions/539911/setting-debconf-selections-for-keyboard-configuration-fails-layout-ends-up-as
    # Delete the keyboard config file before running dpkg-reconfigure. Otherwise config file will not be updated and will stay as "us" default.
    - name: Remove exisiting /etc/default/keyboard
      ansible.builtin.file:
        path: /etc/default/keyboard
        state: absent

    - name: Set keyboard model
      ansible.builtin.debconf:
        name: keyboard-configuration
        question: keyboard-configuration/model
        value: "{{ keyboard_model }}"
        vtype: select
      notify: 
        - reconf keyboard configuration
        - reconf console setup

    - name: Set keyboard variant
      ansible.builtin.debconf:
        name: keyboard-configuration
        question: keyboard-configuration/variant
        value: "{{ keyboard_variant }}"
        vtype: select
      notify: 
        - reconf keyboard configuration
        - reconf console setup

    - name: Set keyboard layout
      ansible.builtin.debconf:
        name: keyboard-configuration
        question: keyboard-configuration/layout
        value: "{{ keyboard_layout }}"
        vtype: select
      notify: 
        - reconf keyboard configuration
        - reconf console setup

    - name: Set keyboard altgr key
      ansible.builtin.debconf:
        name: keyboard-configuration
        question: keyboard-configuration/altgr
        value: "{{ keyboard_altgr }}"
        vtype: select
      notify: 
        - reconf keyboard configuration
        - reconf console setup

    - name: Set keyboard compose key
      ansible.builtin.debconf:
        name: keyboard-configuration
        question: keyboard-configuration/compose
        value: "{{ keyboard_compose }}"
        vtype: select
      notify: 
        - reconf keyboard configuration
        - reconf console setup

    - name: Set keyboard shortcut to kill xserver
      ansible.builtin.debconf:
        name: keyboard-configuration
        question: keyboard-configuration/ctrl_alt_bksp
        value: "{{ keyboard_killx }}"
        vtype: boolean
      notify: 
        - reconf keyboard configuration
        - reconf console setup
    
    - name: Force handlers to run
      ansible.builtin.meta: flush_handlers
###############################################################################
