---
###############################################################################
# [ Should be in chroot env now ]##############################################

- name: Configure new system in chroot environment
  when:
    - ansible_nodename != "localhost"
  tags:
    - config_system
  block:
    - name: Ensure all packages are up to date
      ansible.builtin.apt:
        upgrade: safe
        force_apt_get: true
        autoclean: true
        autoremove: true
        update_cache: true

    - name: Run command to mark APT packages as hold
      ansible.builtin.command:
        cmd: "bash -c '{{ item }}'"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - "apt-mark hold {{ packages_to_mark_hold | join(' ') }}"
      when:
        - ansible_os_family == "Debian"

    - name: Install some basic requirements
      ansible.builtin.apt:
        name:
          - console-setup
          - locales
          - dpkg-dev
          - debconf
          - debconf-utils
          - mdadm
          - dosfstools
          - systemd-cryptsetup
        state: present
        install_recommends: false

    - name: Purge os-prober
      ansible.builtin.apt:
        name:
          - os-prober
        state: absent
        purge: true
      when:
        - ansible_os_family == "Debian"
        - remove_os_prober == true
        
###############################################################################
