---
# [ Install rEFInd Boot Manager ]##############################################
- name: Install rEFInd Boot Manager Block
  when:
    - ansible_nodename != "localhost"
  tags:
    - install_refind
  block:
    - name: Install rEFInd Boot Manager
      ansible.builtin.apt:
        name: 
          - refind
          - git
        state: present
      when:
        - ansible_os_family == "Debian"

    - name: Make sure efivars are mounted
      ansible.posix.mount:
        path: /sys/firmware/efi/efivars
        src: efivarfs
        fstype: efivarfs
        state: ephemeral

    - name: Create Directories for zfs-boot-menu and refind
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        owner: root
        group: root
      loop:
        - "{{ zfs_boot_menu_path }}"
        - "{{ refind_path }}"

    - name: Run command to install rEFInd Boot Manager
      ansible.builtin.command:
        cmd: "{{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - "refind-install --yes"
      when:
        - ansible_os_family == "Debian"

    - name: Copy rEFInd template to /mnt/boot/efi/EFI/zfsbootmenu/refind_linux.conf
      ansible.builtin.template:
        src: refind_linux.conf.j2
        dest: "{{ zfs_boot_menu_path }}/refind_linux.conf"
        owner: "root"
        group: "root"
        mode: "0644"

    # If we're running under legacy bios then rEFInd will be installed
    # to /boot/efi/EFI/BOOT - we want it in /boot/efi/EFI/refind
    - name: Run command to Move rEFInd if under Legacy BIOS
      when:
        - not uefi_mode
      ansible.builtin.command:
        cmd: "{{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - "mvrefind {{ efi_boot_path }}/BOOT {{ refind_path }}"

    - name: Reduce rEFIND boot menu timeout from 20 seconds to new value
      ansible.builtin.replace:
        path: "{{ refind_path }}/refind.conf"
        regexp: '^timeout .*'
        replace: 'timeout {{ refind_boot_menu_timeout }}'

    - name: Create directory for rEFInd theme
      ansible.builtin.file: 
        state: directory
        path: "{{ refind_path }}/themes/{{ refind_theme_name }}/"
        owner: root
        group: root
        
    - name: Fetch rEFInd theme
      ansible.builtin.git:
        clone: true
        repo: "{{ refind_theme_repo }}"
        dest: "{{ refind_path }}/themes/{{ refind_theme_name }}"
        version: master
        force: true

    - name: Config rEFInd to use theme
      ansible.builtin.lineinfile:
        path: "{{ refind_path }}/refind.conf"
        line: "include themes/{{ refind_theme_name }}/theme.conf"
        state: present
        owner: root
        group: root
        mode: '0644'

    - name: Add custom menuentry for ZBM
      ansible.builtin.blockinfile:
        block: |
          menuentry "ZFSBootMenu" {
              loader {{ zfs_boot_menu_path[ efi_boot_mountpoint | length :] }}/vmlinuz-bootmenu
              initrd {{ zfs_boot_menu_path[ efi_boot_mountpoint | length :] }}/initramfs-bootmenu.img
              icon {{ refind_path[ efi_boot_mountpoint | length :] }}/themes/refind-ambience/icons/os_proxmox.png
          }
        insertbefore: "include themes"
        marker: "## {mark} ANSIBLE MANAGED CUSTOM BOOT ENTRY ##"
        path: "{{ refind_path }}/refind.conf"
        prepend_newline: true
        append_newline: true

    - name: Configure display resolution for rEFInd
      ansible.builtin.lineinfile:
        path: "{{ refind_path }}/refind.conf"
        regexp: '^(#+resolution|resolution)'
        line: "resolution {{ refind_resolution }}"
        state: present
      when:
        - refind_resolution is defined
        - refind_resolution|length > 0
    
    - name: Configure directories to exclude from scan for rEFInd
      ansible.builtin.lineinfile:
        path: "{{ refind_path }}/refind.conf"
        regexp: '^(#+dont_scan_dirs|dont_scan_dirs)'
        line: "dont_scan_dirs {{ refind_no_scan_dirs }}"
        state: present
      when:
        - refind_no_scan_dirs is defined
        - refind_no_scan_dirs|length > 0

    - name: Copy startup script with multiple disks template to /boot/efi/startup.nsh
      ansible.builtin.template:
        src: startup.nsh.j2
        dest: "{{ efi_boot_mountpoint }}/startup.nsh"
        owner: "root"
        group: "root"
        mode: "0644"
      when:
        - disk_by_id | length | int > 1
