---
# [ Install Syslinux Boot Loader ]##############################################
- name: Install Syslinux Boot Loader Block
  when:
    - ansible_nodename != "localhost"
  tags:
    - install_syslinux
  block:
    - name: Create Syslinux Directory
      ansible.builtin.file:
        state: directory
        path: "{{ syslinx_path }}"
        owner: root
        group: root

    - name: Install Syslinux Packages
      ansible.builtin.apt:
        name: 
          - syslinux
          - syslinux-common
          - extlinux
          - dosfstools
          - unzip
        state: present
      when:
        - ansible_os_family == "Debian"

    - name: Copy Syslinux Files in place
      ansible.builtin.copy:
        dest: "{{ syslinx_path }}"
        remote_src: true
        src: "/usr/lib/syslinux/modules/bios/"

    - name: Run command to install Syslinux Boot Loader
      ansible.builtin.command:
        cmd: "{{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        # Install extlinux
        - "extlinux --install {{ syslinx_path }}"
      when:
        - ansible_os_family == "Debian"

    - name: Run command to install the syslinux GPTMBR data on each disk device
      ansible.builtin.command:
        cmd: "dd bs=440 count=1 conv=notrunc if=/usr/lib/syslinux/mbr/gptmbr.bin of={{ item }}"
      register: cmd_output
      changed_when:
        cmd_output.rc == 0
      ignore_errors: true
      loop:
        "{{ disk_by_id }}"

    - name: Copy Logo Images and Icons
      ansible.builtin.copy:
        src: "files/{{ item.source }}"
        dest: "{{ item.dest }}"
        owner: "root"
        group: "root"
        mode: "0644"
      with_items:
        - { source: "logo_sm.jpg", dest: "{{ syslinx_path }}/" }
      when:
        - refind_boot_menu_logo  | default(false)
