---
# [ System Tweaks Block ]######################################################
- name: System Tweaks Block
  when:
    - ansible_nodename != "localhost"
  tags:
    - system_tweaks
  block:
    - name: Install ZFS Service Templates
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - zpool-trim@.service   # ZFS zpool trim service
        - zpool-trim@.timer     # ZFS zpool trim service timer unit
        - zpool-scrub@.service  # ZFS zpool scrub service
        - zpool-scrub@.timer    # ZFS zpool scrub service timer unit

    - name: Run commands to enable ZFS Trim Services
      ansible.builtin.command:
        cmd: "{{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - "systemctl enable zpool-trim@{{ root_pool_name }}.service"
        - "systemctl enable zpool-trim@{{ root_pool_name }}.timer"
      when:
        - zfs_pool_trim_systemd_service_enable | default( false) | bool

    - name: Run commands to enable ZFS Scrub Service
      ansible.builtin.command:
        cmd: "{{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - "systemctl enable zpool-scrub@{{ root_pool_name }}.service"
        - "systemctl enable zpool-scrub@{{ root_pool_name }}.timer"
      when:
        - zfs_pool_scrub_systemd_service_enable | default( false) | bool

###############################################################################
# [ ZFS Encryption Unlock Script and Unit File Block ]#########################
- name: ZFS Encryption Unlock Script and Unit File Block
  when:
    - root_pool_encryption | default(false)
    - disk_encryption_type == "native"
    - ansible_nodename != "localhost"
  tags:
    - system_tweaks
  block:
    - name: ZFS encryption script to load the keyfile
      ansible.builtin.template:
        src: "zfs-multi-mount.sh.j2"
        dest: "/usr/bin/zfs-multi-mount.sh"
        owner: root
        group: root
        mode: "755"

    - name: Install ZFS Service Templates for Encryption
      ansible.builtin.template:
        src: "{{ item }}.j2"
        dest: "/etc/systemd/system/{{ item }}"
        owner: root
        group: root
        mode: "644"
      with_items:
        - zfs-load-key.service  # ZFS encryption service to load keyfile

    - name: Run commands to enable ZFS load key service
      ansible.builtin.command:
        cmd: "{{ item }}"
      register: cmd_output
      changed_when: cmd_output.rc == 0
      with_items:
        - "systemctl enable zfs-load-key.service"
