---
###############################################################################
# [ Run Localization Tasks ]##################################################
- name: Run Localization Tasks
  when:
    - ansible_nodename != "localhost"
  tags:
    - localization
  block:
##### LOCALES #####
# Removed the configuration and setting of locales via debconf, as it was not working properly. No plan to chang that currently.

##### TIMEZONE #####
    - name: Install required packages to configure timezone
      ansible.builtin.apt:
        name:
          - tzdata
        state: present

    - name: Set timezone
      ansible.builtin.timezone:
        name: "{{ timezone_area }}/{{ timezone_city }}"
      when: localization_timezone is not none

##### KEYBOARD #####    
    - name: Install required packages to configure keyboard
      ansible.builtin.apt:
        name:
          - keyboard-configuration
          - console-setup
        state: present

    - name: Set keyboard configuration in /etc/default/keyboard
      ansible.builtin.template:
        src: keyboard.j2
        dest: /etc/default/keyboard
        force: true
        owner: root
        group: root
        mode: '0644'
      notify: Setupcon
      

    
    - name: Force handlers to run
      ansible.builtin.meta: flush_handlers
###############################################################################