---
####################################################################################################
# This script is for installing and configuring ZFS on Root from an Debian Live CD.
#
# Usage: --extra-vars='{"disk_devices": [sda, sdb], host_name: "mynewpc", passphrase: "mys3cret"}
#
# The "disk_devices" specifies the devices to erase all partitions from and install ZFS filesystem on.
# The simple "sda" style references will be converted to "disk_by_id" references.
#
# If the required "disk_devices", or "host_name" is not specified, you will be prompted to enter it.
######################################################################################################

# [ Load up the secret files ]#####################################################################
- name: Include Secret Files
  ansible.builtin.include_vars: "{{ item }}"
  tags: ["always"]
  loop:
    - secrets/main.yml
  no_log: "{{ no_log_secrets | default(true) }}"

- name: Include Task Files to Configure and Setup Live CD Enviroment and Base System
  ansible.builtin.include_tasks: "{{ task_names }}"
  tags: ["always"]
  loop:
    - 01_test_virtualbox.yml
    - 01_basic_checks.yml
    ### - 00_DEBUGSTUFF.yml
    - 02_confirm_defaults.yml
    - 03_install_zfs_packages.yml
    - 04_clear_partition_tables.yml
    - 05_create_partitions.yml
    - 06_0_create_luks.yml
    - 06_create_pools.yml
    - 07_create_filesystems.yml
    - 08_create_datasets.yml
    - 09_0_config_system.yml
  loop_control:
    label: "{{ task_names }}"
    loop_var: task_names

- name: Include Task Files to Configure new System in chroot
  vars:
    ansible_port: 8922
  ansible.builtin.include_tasks: "{{ task_names }}"
  tags: ["always"]
  loop:
    - 09_1_config_system.yml
    - 10_install_zfs.yml
    - 11_config_boot_filesystem.yml
    - 12_3-install_refind.yml
    - 12_4-install_syslinux.yml
    - 12_5-install_zfsbootmenu.yml
    - 12_6-config_swap.yml
    - 12_7-system_tweaks.yml
    - 13_first_boot_prep.yml
  loop_control:
    label: "{{ task_names }}"
    loop_var: task_names

- name: Include Task Files to Reboot, Reconnect and Finalize new System Config
  ansible.builtin.include_tasks: "{{ task_names }}"
  tags: ["always"]
  loop:
    - 15_unmount_chroot.yml
    - 16_restart_remote.yml
    - 17_localization.yml
    - 18_enable_dropbear.yml
    - 18_5-config_LVM.yml
    - 19_final_setup.yml
    - 20_restart_remote_final.yml
  loop_control:
    label: "{{ task_names }}"
    loop_var: task_names