---
- name: "Create skeleton home directory structure"
  ansible.builtin.copy:
    src: "/etc/skel/."
    dest: "/home/{{ item.item.user_id }}"
    owner: "{{ item.item.user_id }}"
    group: "{{ item.item.user_id }}"
    mode: "0700"
    remote_src: true
  when: item.changed
  with_items: "{{ home_dirs.results }}"
  loop_control:
    label: "/home/{{ item.item.user_id }}"

- name: "Force change password"
  ansible.builtin.command: "chage -d 0 {{ item.item.user_id }}"
  when: item.changed
  with_items: "{{ accounts.results }}"
  loop_control:
    label: "{{ item.item.user_id }}"

- name: "Restart sshd"
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: "reconf locales"
  ansible.builtin.command:
    cmd: "dpkg-reconfigure --frontend noninteractive locales"
  register: cmd_output
  changed_when: cmd_output.rc == 0

- name: "reconf tzdata"
  ansible.builtin.command:
    cmd: "dpkg-reconfigure --frontend noninteractive tzdata"
  register: cmd_output
  changed_when: cmd_output.rc == 0

- name: "reconf keyboard configuration"
  ansible.builtin.command:
    cmd: "dpkg-reconfigure --frontend noninteractive keyboard-configuration"
  register: cmd_output
  changed_when: cmd_output.rc == 0

- name: "reconf console setup"
  ansible.builtin.command:
    cmd: "dpkg-reconfigure --frontend noninteractive console-setup"
  register: cmd_output
  changed_when: cmd_output.rc == 0

